### ISSUE TITLE
clean up export_data module

### ISSUE THREAD

**Issue by alee** [comses/citation#24]
A few guidelines:

1. avoid issuing Platform and Sponsor `all` queries for every publication
2. couple header + row values better - currently they are in two distinct data structures that can very easily get out of sync and are difficult to maintain
3. consider creating some kind of stateful class & improve the API between the header / row value generation
4. use `values_list(flat=True)` instead of generating a tuple that you index
5. replace `get_attribute_values` and `generate_boolean_list` with list comprehensions

**Comment by cpritcha** [comment]
No longer applicable.
