### ISSUE TITLE
need to add publication_id field in AuditLog table

### ISSUE THREAD

**Issue by dhruvilpatel** [comses/citation#9]
@alee

**Comment by alee** [comment]
1. Make a schema migration that creates a dedicated `AuditLog.publication` ForeignKey. 
2. Make a data migration that moves the publication ID in AuditLog.payload into the dedicated `AuditLog.publication` field. You can leave the data in AuditLog.payload untouched for now, we may go through and delete them all later after we're confident the data migration was correct.
3. You can then reduce the number of queries by doing a prefetch on the Publication's audit logs.

**Comment by dhruvilpatel** [comment]
Are we adding the Publication Model as a ForeignKey in AuditLog or are we adding a simple integer field name pub_id in AuditLog and move the Publication_Id from the payload JSON field into this new field using migration?

**Comment by cpritcha** [comment]
You should use the ForeignKey field type otherwise you will not be able to prefetch. [ForeignKey](https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.ForeignKey) has a `db_constraint` that you could turn off.

**Comment by cpritcha** [comment]
Done. There is a `pub_id` field now.
